### ISSUE TITLE
Possible missing rootseq.h file

### ISSUE THREAD

**Issue by aganir** [alpertron/calculators#10]
It seems that *rootseq.h* file is not present in the repository. 
However *intpolfact.c*, *polfact.c*, *quintics.c* and *rootseq.c* try to include *rootseq.h*. 
Executing *make* in Linux or compiling *ConsoleApplication1.vcxproj* with VS2019 both results as errors with missing *rootseq.h* so it is most probably required.

Could you please add *rootseq.h* file?
(Or in the case header file is intended to be generated instruction how that can be done?)

**Comment by alpertron** [comment]
I forgot to add this file. I've just added it.

Thanks for catching this.

**Comment by aganir** [comment]
Thank you for adding the file and for the prompt response
