### ISSUE TITLE
linking error in building

### ISSUE THREAD

**Issue by themaddoctor** [alpertron/calculators#11]
gcc expression.oto partition.oto errors.oto bigint.oto division.oto baseconv.oto karatsuba.oto modmult.oto sqroot.oto \
rootseq.oto quintics.oto bigrational.oto output.oto polynomial.oto polfact.oto bignbr.oto showtime.oto from_musl.oto inputstr.oto fft.oto test_polfact.oto -lm -o polfact
rootseq.oto: In function `getRootsPolynomial':
rootseq.c:(.text+0x1c49): undefined reference to `FactorPolyOverIntegers'
rootseq.c:(.text+0x1c4f): undefined reference to `factorInfoInteger'
rootseq.c:(.text+0x1c67): undefined reference to `factorInfoInteger'
rootseq.c:(.text+0x2924): undefined reference to `polyInteger'
rootseq.c:(.text+0x292a): undefined reference to `factorInfoInteger'
quintics.oto: In function `QuinticEquation':
quintics.c:(.text+0x1530): undefined reference to `FactorPolyOverIntegers'
quintics.c:(.text+0x1536): undefined reference to `factorInfoInteger'
quintics.c:(.text+0x1561): undefined reference to `factorInfoInteger'
polfact.oto: In function `polyFactText':
polfact.c:(.text+0xa6f): undefined reference to `factorInfoInteger'
polfact.c:(.text+0xde0): undefined reference to `factorInfoInteger'
polfact.c:(.text+0xec0): undefined reference to `FactorPolyOverIntegers'
collect2: error: ld returned 1 exit status
Makefile:64: recipe for target 'polfact' failed
make: *** [polfact] Error 1

on 64-bit linux with gcc 7.3 etc.

**Comment by themaddoctor** [comment]
"intpolfact.oto" is missing from the relevant lines in the make file.

**Comment by alpertron** [comment]
I've just uploaded the new version of Makefile and also changed quintics.c that had a warning.
