### ISSUE TITLE
negatives partial results in expressions

### ISSUE THREAD

**Issue by dhalsimax** [alpertron/calculators#12]
Hello,

please try this:
68%67
-68%67
(-68)%67
in the page https://www.alpertron.com.ar/ECM.HTM
you will get:
1 = 1
-1 = -1
0 = 0

then try this:
(51^3+12)^3-(117^2+33140)^2
you will get no result...

It seems since the updates of mars there some issues with negative numbers and expressions(parenthesis) I remember that in february worked very well instead

Regards Massimo.

**Comment by alpertron** [comment]
I've just uploaded a new version which fixes this problem. Please refresh the page so you read the date 23 April 2020.

**Comment by dhalsimax** [comment]
Nice job thanks.
