### ISSUE TITLE
Parenthesis errors on moudulus

### ISSUE THREAD

**Issue by dhalsimax** [alpertron/calculators#13]
I was doing an exercise... it was a hensel lift formula:
(273663-10397*modinv(3*273663**2,(1223231 * 1611469)**2))%((1223231 * 1611469)**2)
Please try this you will get no result.
However for some other formulas after the modulus expressions still got no results.

**Comment by alpertron** [comment]
I've just fixed some issues regarding the expression calculator stack. Now the expression you wrote above works OK, if you add a multiplication sign between 10397 and modinv.

**Comment by dhalsimax** [comment]
many thanks.
