### ISSUE TITLE
Adding new factor during computation in https://www.alpertron.com.ar/ECM.HTM

### ISSUE THREAD

**Issue by dhalsimax** [alpertron/calculators#14]
using the button "MORE" and inserting the new factor numbers inserted got capped at 17'th digit.

**Comment by alpertron** [comment]
I started to factor **n(10^50+3)*b(10^60+7)** which has these two big prime factors. While the application was trying to factor it using ECM, I pressed the **More** button, entered **100000000000000000000000000000000000000000000000151** and then pressed the **New factor** button. The application finished the factorization session successfully.

**Comment by dhalsimax** [comment]
Hi, you right, have you tried with Firefox?

**Comment by alpertron** [comment]
I've just done it on Firefox and it works OK, both copying the number and typing it.

**Comment by dhalsimax** [comment]
Ok you right, i was wrong pasting an hexadecimal value that seems isn't supported.
