### ISSUE TITLE
musl.h is missing

### ISSUE THREAD

**Issue by oppressionslayer** [alpertron/calculators#15]
gcc -D_USING64BITS_ -c -Os -o fft.oto fft.c
gcc -D_USING64BITS_ -c -Os -DDEBUG_CODE=9 -o test_polfact.oto test.c
gcc -D_USING64BITS_ -c -Os -o intpolfact.oto intpolfact.c
intpolfact.c:28:10: fatal error: musl.h: No such file or directory
   28 | #include "musl.h"
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:71: intpolfact.oto] Error 1

I tried installing musl-dev, but that didn't help. is there another library i'm missing to get this to be installed?

**Comment by alpertron** [comment]
I've just uploaded the missing file musl.h. Thanks for catching the error.

**Comment by oppressionslayer** [comment]
This fixed it, i can now compile without error under ubuntu. Thanks!
