### ISSUE TITLE
question of  the implementation of pohlig-hellman

### ISSUE THREAD

**Issue by loccs-faker** [alpertron/calculators#2]
recentlly,I've learned the Pohlig-hellman  algorithm. I understand that it applies to groups whose order is a prime power. Usually,the modulus is a prime number,so the group order is (p-1). But I  don't know how did you deal with the composite moduli(for example, modulus is p#(product of all primes less or equal than p)). could you please make a brief explanation?

**Comment by alpertron** [comment]
The application factors the composite number, computes the discrete logarithm modulo the prime factors and then reconstruct the final discrete logarithm modulo the composite number by using the Chinese Remainder Theorem.
