### ISSUE TITLE
QUAD.HTM down?

### ISSUE THREAD

**Issue by hvds** [alpertron/calculators#21]
At the moment attempting to reach [QUAD](https://www.alpertron.com.ar/QUAD.HTM) is redirecting to [the homepage](https://www.alpertron.com.ar/).

Apologies that this is probably reporting a website issue rather than a calculator issue, but I understand from [this](https://math.stackexchange.com/questions/487051) that the comment form on the website is not a reliable way to contact you.

**Comment by alpertron** [comment]
I typed https://www.alpertron.com.ar/QUAD.HTM in both Chrome and Firefox on Windows 11, and in both cases the calculator appeared on screen. I also refreshed the page and the redirection did not occur.

**Comment by hvds** [comment]
Hmm, I tried with `lynx` instead, and it briefly popped up "Bad HTML, use -trace to diagnose" and then redirected in the same way. But after trying it a couple of times, the error now appears to have gone away, and it is giving me the expected form (with a warning that I would need to enable JS in lynx).

I did capture a copy with `wget`, I think before the problem disappeared. I'll see if I can find an HTML validator to throw it at.

I'm running Firefox under Ubuntu Linux, Firefox is still redirecting (but may be seeing cached data).

**Comment by hvds** [comment]
Hmm, I have rebooted, but Firefox still redirects.

The [W3C HTML validator](https://validator.w3.org/) sees no problem with the page captured by `wget`.

I also have Chrome available, and that shows the calculator without a problem.

Given you don't see a problem with Firefox, and I can access it via another browser if I need to, I guess I should give up on this - I don't know enough about Firefox's built-in debugger to diagnose it that way.

Apologies if this wasted your time, and thanks again for making your calculators available.
