### ISSUE TITLE
BlockLanczos loop/feedback

### ISSUE THREAD

**Issue by hvds** [alpertron/calculators#22]
I am trying to factorize the number "945 963552 037903 692304 185224 846621 632975 583515 796777 435749 818606 681847 712555 267388 667817", which uses SIQS. It spent 45 minute finding relations (50312 primes, sieve limit 99112, multiplier 1, factor base 1305593) and has now spent 24 minutes so far solving the 48551 × 45972 congruence matrix.

1) The display repeatedly shows "Linear algebra progress" going up towards 100%, then resetting to 0%, repeating about every 24s. Would it be possible to show also the `ctr` and `seed` in some way to show more of what is happening?

2) I note that the code has no termination condition on:
```
    while (BlockLanczos(seed + ctr) == false)
    {   // Block Lanczos does not work with this seed. Try another one.
      seed++;
    }
```
I don't know anything about the BlockLanczos algorithm, is it possible that this will never terminate? On previous SIQS factorizations this phase always seemed pretty much instantaneous. At 24s per cycle, I guess it has done 60 cycles so far.

**Comment by hvds** [comment]
It is curious that my normal factorization package also failed using SIQS on this (Dana Jacobsen's [Math::Prime::Util::GMP](https://github.com/danaj/Math-Prime-Util-GMP/blob/master/simpqs.c)), but a collaborator on Windows _was_ able to factorize this for me using `yafu-x86`:
```
starting SIQS on c87: 945963552037903692304185224846621632975583515796777435749818606681847712555267388667817
...
SIQS elapsed time = 600.2483 seconds.
Total factoring time = 680.8489 seconds
 
***factors found***
 
P32 = 21744489429639490589994133152841
P56 = 43503599157793016488853604280294370203685375046705264737
```

**Comment by hvds** [comment]
I note that Alpertron is reporting:
```
Written by Dario Alpern. Last updated 18 December 2022.
```

The collaborator also tried Alpertron, and was able to get a factorization. But for him it reports:
```
Written by Dario Alpern. Last updated on 31 October 2022.
```

So I suspect one of the recent commits has caused an issue, presumably cc750afc1c1c or 9c3c9840f2.

**Comment by alpertron** [comment]
Thanks for your comments. At this moment I have a lot of work, so I cannot help you in the next few days.

**Comment by hvds** [comment]
> Thanks for your comments. At this moment I have a lot of work, so I cannot help you in the next few days.

No worries, if I get a chance I'll take a look myself, but I anticipate a steep learning curve.

**Comment by alpertron** [comment]
I've just uploaded the new version to the Web server with the bug fix.

Please refresh the page so you can read 6 February 2023, then try again.

**Comment by hvds** [comment]
Thanks, that successfully factored it with SIQS.

I assume the fix was in one or both of the commits 5d1b04fc1a and 7a96ff111d, but it is not clear what the actual bug was - was it one of the signed/unsigned conversions?

**Comment by alpertron** [comment]
The error was in the colexchange function. Sometimes there was an overwrite of the bits being exchanged. The problem did not affect small factorizations using SIQS.

**Comment by hvds** [comment]
Thank you.
