### ISSUE TITLE
Integer factorization calculator feature request/how to add other bit(wise) operators

### ISSUE THREAD

**Issue by 0joshuaolson1** [alpertron/calculators#3]
I like the additional operators that https://defuse.ca/big-number-calculator.htm supports:
- SHL/<<
- SHR/>> (signed)
- XOR
- | for OR
- & for AND

Should I try adding them (and a couple others) to ECM(C).HTM, would you like to, or neither?

**Comment by alpertron** [comment]
The expression evaluator already includes the "or" and "and" operators. For example, 23 or 43 = 63, 23 and 43 = 3. The other three are easy to add.

**Comment by 0joshuaolson1** [comment]
Cool. I was just thinking NOT/!, and maybe unsigned SHR/>> (but when is the confusing extra choice useful? hm..).

With XOR, the Help ought to clarify that `^` is different (but you don't document `|` or `&`, so it may be OK).

**Comment by alpertron** [comment]
In the help there is a section named Expressions which includes the text "AND, OR, NOT for binary logic."

**Comment by 0joshuaolson1** [comment]
Whoops, I meant `!` as an alias for NOT. But again, leaving out aliases is simpler and avoids the potential `^` ambiguity.

**Comment by alpertron** [comment]
The expression evaluator also supports hexadecimal constants such as 0x45, and you can also select hexadecimal output, but it is hidden in the configuration menu. Maybe I also have to add the decimal/hexadecimal output option to the Wizard.

**Comment by 0joshuaolson1** [comment]
I just thought of the sign operator, but that may be going too far, since bit twiddling and naming expressions for reuse is going too far into programming.

**Comment by alpertron** [comment]
I added the missing operators (XOR, SHL and SHR) and also changed the Wizard so you can use hexadecimal output.

**Comment by 0joshuaolson1** [comment]
Thanks, it looks good to me! A couple small things that surprised me:

- I expected hex output to also have the `0x` prefix, so I wasn't sure at first it remembered the setting
- the wizard saves the new hex/decimal setting immediately after step 1 (either way works)

**Comment by alpertron** [comment]
Hexadecimal output is marked in monospace font.
