### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by berXpert** [alpertron/calculators#4]
It looks like there are a couple of files missing (aprtcle.c, batch.c, batch.h), can you check them in?

Files that requires batch.h are, for example: fsquares.c, fcubes.c

**Comment by alpertron** [comment]
I have just uploaded batch.c and batch.h. The other file is not needed in the project.

**Comment by berXpert** [comment]
Thanks, now I can compile the code. I removed the other file from the project list and it compiled.

**Comment by zhonskate** [comment]
I have a problem regarding compilation as well. 
It seems I'm missing the file SDL.h (it is called from _gausspr.c_ and _ulam.c_).

I have to say that I haven't used C a lot and I'm maybe messing up the compilation. Could you tell me the proper way to compile and run the program?
