### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by tgiaki** [alpertron/calculators#5]
I'm interested in your code, but I can't understand how to use it: I'm using Typescript so I'd need the javascript version of the Polynomial Factorization program, or maybe you can explain the algorithm you used in there so I can re-write it in my way. Thanks. Great programs man!

**Comment by alpertron** [comment]
I have written the code in C. Then Emscripten converts that to Asm.js which can be interpreted by the Web browser. I also use LLVM to generate WebAssembly.

**Comment by tgiaki** [comment]
So where is all the code about Polynomial Factorization? All into asm.js? Cause I can see more file *.js but no one seem to have into the right algorithm. Great job man!

**Comment by alpertron** [comment]
The source code is located at polfact.c . Then it uses other C modules for big number operations.

**Comment by alpertron** [comment]
You can look at batch file a.bat what files are compiled.

**Comment by tgiaki** [comment]
So I bring all files polfact.c plus his dependencies and the I can translate it into JavaScript? Cause I need only that programs not all the others.

**Comment by alpertron** [comment]
Yes.

**Comment by alpertron** [comment]
I want to add polynomial factorization over the integers, but this requires adding more supporting functions first, so it will take some time.

**Comment by tgiaki** [comment]
I thought that the factorization over the integers was more easy to done because if you have an irreducible polynomial you keep it as it is while factorizing over some modulo we've got more freedom changing the coefficients modulo some number or changing them sign, but it seems I was wrong.

**Comment by alpertron** [comment]
Factoring over the integers is a lot more complex than factoring in Zp.

**Comment by tgiaki** [comment]
Child you explain the difference in the algorithms over integers and over Zp? I'm try to write some algorithm to factorizing over Zp (I'm using typescript) but I can't understand the correct way to start, it's also not so easy over Zp starting from nothing.

**Comment by alpertron** [comment]
My code uses Cantor-Zassenhaus algorithm. There are faster algorithms but they require more memory.
