### ISSUE TITLE
Compile in Linux or mac os x

### ISSUE THREAD

**Issue by fact0real** [alpertron/calculators#6]
Hey
Dear aplertron,
It seems that we can compile and use this nice calculator in Windows, please add Makefile for compile source code in **Linux** of Mac os x.

**Comment by alpertron** [comment]
The output of the project is JavaScript and WebAssembly for the Web site. I use Visual Studio for debugging the code.

I do not have Mac OS X, but I could try adding a Makefile for Bash for Windows. I think that should be similar.

**Comment by alpertron** [comment]
I've just added a Makefile which generates several executable files from the source code. I tested on bash for Windows and worked OK.

There was a warning when I uploaded this Makefile to Git indicating that the LF were replaced by CR-LF.

I do not know if that could generate problems when running in Mac OS X.
